// ReSharper disable NotAccessedField.Global
// ReSharper disable MemberCanBePrivate.Global

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Itinero.Transit.Api.Models
{
    /// <summary>
    /// A segment represents a part of the journey, e.g. one link where you take the train    
    /// </summary>
    [JsonObject(ItemNullValueHandling = NullValueHandling.Ignore)]
    public class Segment
    {
        /// <summary>
        /// Constructor for an in-vehicle segment
        /// </summary>
        /// <param name="departure"></param>
        /// <param name="arrival"></param>
        /// <param name="vehicle"></param>
        /// <param name="headSign"></param>
        /// <param name="intermediateStops"></param>
        /// <exception cref="ArgumentNullException"></exception>
        internal Segment(TimedLocation departure, TimedLocation arrival,
            string vehicle, string headSign, List<TimedLocation> intermediateStops)
        {
            Departure = departure;
            Arrival = arrival;
            Vehicle = vehicle;
            Headsign = headSign;
            if (Vehicle == null)
            {
                throw new ArgumentNullException(nameof(Vehicle));
            }

            Generator = null;
            Coordinates = new List<Coordinate>();
            
            AllStops = intermediateStops;
            if (Arrival.Time != null && Departure.Time != null)
            {
                TotalTime = (uint) (Arrival.Time.Value - Departure.Time.Value).TotalSeconds;
            }
            else
            {
                TotalTime = 0;
            }

            if (intermediateStops != null)
            {
                foreach (var intermediateStop in intermediateStops)
                {
                    Coordinates.Add(new Coordinate(intermediateStop.Location.Lat, intermediateStop.Location.Lon));
                }
            }
        }

        /// <summary>
        /// Constructor for a segment generated by an othermode, e.g. a walk, cycling, ...
        /// </summary>
        internal Segment(TimedLocation departure, TimedLocation arrival, string generator, List<Coordinate> coordinates,
            uint totalTime, string license =null)
        {
            Departure = departure;
            Arrival = arrival;
            Vehicle = null;
            Headsign = null;
            Generator = generator;
            Coordinates = coordinates;
            TotalTime = totalTime;
            License = license;
        }
        
        /// <summary>
        /// Constructor for a segment generated by an othermode, e.g. a walk, cycling, ... but with a reference to coordinates
        /// </summary>
        internal Segment(TimedLocation departure, TimedLocation arrival, string generator, uint coordinatesReference,
            uint totalTime, string license =null)
        {
            Departure = departure;
            Arrival = arrival;
            Vehicle = null;
            Headsign = null;
            Generator = generator;
            Coordinates = null;
            CoordinateReference = coordinatesReference;
            TotalTime = totalTime;
            License = license;
        }

        /// <summary>
        /// The departure location.
        /// </summary>
        public TimedLocation Departure { get; }

        /// <summary>
        /// The arrival location.
        /// </summary>
        public TimedLocation Arrival { get; }

        /// <summary>
        /// All stops where the traveller passes in this segment.
        /// This include the departure and arrival station of the segment,
        /// but also every stop the traveller just passes through without getting on/off
        /// 
        /// This field is mainly meant to visualize the journey on maps.
        /// </summary>
        public List<TimedLocation> AllStops { get; }

        /// <summary>
        /// The identifier of the vehicle (the global trip id).
        /// Meant for machines
        /// </summary>
        public string Vehicle { get; }

        /// <summary>
        /// The name of the train, e.g. its destination.
        /// Meant for humans
        /// </summary>
        public string Headsign { get; }

        /// <summary>
        /// If this segment is routed over the OSM network or some other special case,
        /// the generator description will be passed in here as to know what routing engine was used.
        /// </summary>
        public string Generator { get; }

        /// <summary>
        /// Either:
        /// - The path to walk/bike/... to the stop or destination. This route is generated by 'Generator'
        /// - OR The coordinates of the intermediate stops if on a vehicle; they will be identical to
        ///     IntermediateStops.Select(stop => (stop.Location.Lat, stop.Location.Lon))
        /// </summary>
        public List<Coordinate> Coordinates { get; }
        
        /// <summary>
        /// If provided, the coordinates for this reference can be found in the queryresult, at
        /// result["CommonCoordinates"][CoordinateReference]
        /// </summary>
        public uint? CoordinateReference { get; }

        /// <summary>
        /// Indicates how much time (in seconds) is spent in this segment
        /// </summary>
        public uint TotalTime { get; }

        /// <summary>
        /// The license of this segment. Note that different parts of the journey can have different copyrights.
        /// E.g. the walks are typically generated using the map data of OSM (or some other generator),
        /// while in-journey parts might have copyright by the PTO, ...
        /// </summary>
        public string License { get; }
    }
}