// ReSharper disable NotAccessedField.Global
// ReSharper disable MemberCanBePrivate.Global

using System;
using System.Collections.Generic;

namespace Itinero.Transit.Api.Models
{
    /// <summary>
    /// A segment represents a part of the journey, e.g. one link where you take the train    
    /// </summary>
    public class Segment
    {
        internal Segment(TimedLocation departure, TimedLocation arrival,
            string vehicle, string headSign, List<TimedLocation> intermediateStops)
        {
            Departure = departure;
            Arrival = arrival;
            Vehicle = vehicle;
            Headsign = headSign;
            if (Vehicle == null)
            {
                throw new ArgumentNullException(nameof(Vehicle));
            }

            Generator = null;
            Coordinates = new List<Coordinate>();
            AllStops = intermediateStops;
            if (intermediateStops != null)
            {
                foreach (var intermediateStop in intermediateStops)
                {
                    Coordinates.Add(new Coordinate(intermediateStop.Location.Lat, intermediateStop.Location.Lon));
                }
            }
        }

        internal Segment(TimedLocation departure, TimedLocation arrival, string generator, List<Coordinate> coordinates)
        {
            Departure = departure;
            Arrival = arrival;
            Vehicle = null;
            Headsign = null;
            Generator = generator;
            Coordinates = coordinates;
        }

        /// <summary>
        /// The departure location.
        /// </summary>
        public TimedLocation Departure { get; }

        /// <summary>
        /// The arrival location.
        /// </summary>
        public TimedLocation Arrival { get; }

        /// <summary>
        /// All stops where the traveller passes in this segment.
        /// This include the departure and arrival station of the segment,
        /// but also every stop the traveller just passes through without getting on/off
        /// 
        /// This field is mainly meant to visualize the journey on maps.
        /// </summary>
        public List<TimedLocation> AllStops { get; }

        /// <summary>
        /// The identifier of the vehicle (the global trip id).
        /// Meant for machines
        /// </summary>
        public string Vehicle { get; }

        /// <summary>
        /// The name of the train, e.g. its destination.
        /// Meant for humans
        /// </summary>
        public string Headsign { get; }

        /// <summary>
        /// If this segment is routed over the OSM network or some other special case,
        /// the generator description will be passed in here as to know what routing engine was used.
        /// </summary>
        public string Generator { get; }

        /// <summary>
        /// Either:
        /// - The path to walk/bike/... to the stop or destination. This route is generated by 'Generator'
        /// - OR The coordinates of the intermediate stops if on a vehicle; they will be identical to
        ///     IntermediateStops.Select(stop => (stop.Location.Lat, stop.Location.Lon))
        /// </summary>
        public List<Coordinate> Coordinates { get; }
    }
}