name: staging

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add GitHub Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/anyways-open/index.json -n anyways -u xivk -p ${{secrets.PACKAGES_SECRET }} --store-password-in-clear-text
    
    - name: Add GitHub Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/itinero/index.json -n itinero -u xivk -p ${{secrets.PACKAGES_SECRET }} --store-password-in-clear-text
    
    - name: Add GitHub Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/osmsharp/index.json -n osmsharp -u xivk -p ${{secrets.PACKAGES_SECRET }} --store-password-in-clear-text

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal  

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u anywaysbot --password-stdin

       
    - name: Publish generator project
      run: dotnet publish -c release
      working-directory: ./src/Itinero.Transit.Api/
    - name: Build the Generator Docker image
      run: docker build . --file Dockerfile --tag anywaysopen/transit-routing-api:staging --tag anywaysopen/transit-routing-api:staging-0.$GITHUB_RUN_NUMBER
      working-directory: ./src/Itinero.Transit.Api/
    - name: Publish on dockerhub with staging tag.
      run: docker push anywaysopen/transit-routing-api:staging
    - name: Publish on dockerhub with the version number.
      run: docker push anywaysopen/transit-routing-api:staging-0.$GITHUB_RUN_NUMBER 
 

      

